plugins {
    id "groovy"
    id "org.grails.grails-gsp"
    id "org.grails.grails-web"
    id "war"
    id "idea"
    id "com.bertramlabs.asset-pipeline"
    id "org.grails.grails-plugin"
    id "application"
    id "eclipse"
    id "maven-publish"
}

group = "grails.turbo"
version = project.findProperty('version')

repositories {
    mavenCentral()
    maven { url "https://repo.grails.org/grails/core/" }
}

dependencyLocking {
    lockAllConfigurations()
}

configurations {
    configureEach {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'org.seleniumhq.selenium') {
                details.useVersion(libs.versions.selenium.get())
                details.because('Grails BOM aligns some Selenium artifacts to 4.1.4; mixing with 4.16.x causes NoClassDefFoundError (e.g. HasTouchScreen)')
            }
        }
    }
}

dependencies {
    implementation(libs.grails.core)
    implementation(libs.grails.logging)
    implementation(libs.grails.plugin.databinding)
    implementation(libs.grails.plugin.i18n)
    implementation(libs.grails.plugin.interceptors)
    implementation(libs.grails.plugin.rest)
    implementation(libs.grails.plugin.services)
    implementation(libs.grails.plugin.url.mappings)
    implementation(libs.grails.web.boot)
    implementation(libs.gsp)
    implementation(libs.hibernate5)
    implementation(libs.scaffolding)
    implementation(libs.hibernate.core)
    implementation(libs.spring.boot.autoconfigure)
    implementation(libs.spring.boot.starter)
    implementation(libs.spring.boot.starter.actuator)
    implementation(libs.spring.boot.starter.logging)
    implementation(libs.spring.boot.starter.tomcat)
    implementation(libs.spring.boot.starter.validation)
    implementation(libs.spring.boot.starter.websocket)
    compileOnly(libs.micronaut.inject.groovy)
    console(libs.grails.console)
    runtimeOnly(libs.asset.pipeline.grails)
    runtimeOnly(libs.h2)
    runtimeOnly(libs.jaxb.api)
    runtimeOnly(libs.tomcat.jdbc)
    runtimeOnly(libs.jansi)
    runtimeOnly(libs.el.impl)
    testImplementation(libs.micronaut.inject.groovy)
    testImplementation(libs.grails.gorm.testing.support)
    testImplementation(libs.grails.web.testing.support)
    testImplementation(libs.spock.core)
    testImplementation(libs.micronaut.http.client)

    testImplementation(libs.geb)
    testImplementation(libs.bundles.selenium.test)
    testRuntimeOnly(libs.bundles.selenium.drivers)
}

application {
    mainClass.set("grails.turbo.Application")
}

java {
    sourceCompatibility = JavaVersion.toVersion(libs.versions.java.get())
}

jar {
    archiveClassifier = ''
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
            versionMapping {
                usage('java-api') {
                    fromResolutionOf('runtimeClasspath')
                }
                usage('java-runtime') {
                    fromResolutionResult()
                }
            }
            pom {
                name = 'Grails Turbo Plugin'
                description = 'Hotwired Turbo integration for Grails applications'
                url = 'https://github.com/philippreston/grails-turbo'
                licenses {
                    license {
                        name = 'Apache License 2.0'
                        url = 'https://www.apache.org/licenses/LICENSE-2.0'
                    }
                }
                scm {
                    connection = 'scm:git:git://github.com/philippreston/grails-turbo.git'
                    developerConnection = 'scm:git:ssh://github.com/philippreston/grails-turbo.git'
                    url = 'https://github.com/philippreston/grails-turbo'
                }
            }
        }
    }
    repositories {
        maven {
            name = 'GitHubPackages'
            url = uri('https://maven.pkg.github.com/philippreston/grails-turbo')
            credentials {
                username = project.findProperty('gpr.user') ?: System.getenv('GITHUB_ACTOR')
                password = project.findProperty('gpr.key') ?: System.getenv('GITHUB_TOKEN')
            }
        }
    }
}

tasks.withType(Test) {
    useJUnitPlatform()
    systemProperty "geb.env", System.getProperty('geb.env')
    systemProperty "geb.build.reportsDir", reporting.file("geb/integrationTest")
}

assets {
    packagePlugin = true
    minifyJs = true
    minifyCss = true
}
