repositories {
    mavenCentral()
    maven { url "https://repo.grails.org/grails/core/" }
}

dependencies {
    implementation(libs.asset.pipeline.gradle)
    implementation(libs.grails.gradle.plugin)
    implementation(libs.hibernate5.gradle.plugin)
}

configurations.configureEach {
    // Needed for Gradle compatibility with Grails Gradle Plugin.
    // (Only needed when there are files in buildSrc/src/*/groovy)
    resolutionStrategy.force "org.codehaus.groovy:groovy-xml:${GroovySystem.version}"
}
